// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.SlotMachineSimulator
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("total_spins")]
        public long TotalSpins { get; set; }

        [JsonProperty("num_reels")]
        public long NumReels { get; set; }

        [JsonProperty("bet_per_spin")]
        public long BetPerSpin { get; set; }

        [JsonProperty("spins")]
        public Spin[] Spins { get; set; }

        [JsonProperty("total_bet")]
        public long TotalBet { get; set; }

        [JsonProperty("total_winnings")]
        public long TotalWinnings { get; set; }

        [JsonProperty("net_profit")]
        public long NetProfit { get; set; }

        [JsonProperty("wins")]
        public long Wins { get; set; }

        [JsonProperty("losses")]
        public long Losses { get; set; }

        [JsonProperty("win_percentage")]
        public long WinPercentage { get; set; }

        [JsonProperty("available_symbols")]
        public AvailableSymbol[] AvailableSymbols { get; set; }
    }

    public partial class AvailableSymbol
    {
        [JsonProperty("symbol")]
        public string Symbol { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("payout_multiplier")]
        public long PayoutMultiplier { get; set; }
    }

    public partial class Spin
    {
        [JsonProperty("spin_number")]
        public long SpinNumber { get; set; }

        [JsonProperty("reels")]
        public Reel[] Reels { get; set; }

        [JsonProperty("bet")]
        public long Bet { get; set; }

        [JsonProperty("payout")]
        public long Payout { get; set; }

        [JsonProperty("win_type")]
        public string WinType { get; set; }

        [JsonProperty("is_win")]
        public bool IsWin { get; set; }
    }

    public partial class Reel
    {
        [JsonProperty("symbol")]
        public string Symbol { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }
    }
}
